[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.5", features = ["ws"] }
axum-auth = "0.7.0"
axum-extra = { version = "0.9.3", features = ["typed-header"] }
axum-server = { version = "0.7.1" }
dotenv = "0.15.0"
futures-util = "0.3.30"
jsonwebkey = { version = "0.3.5", features = ["jsonwebtoken"] }
jsonwebtoken = "8"
reqwest = "0.12.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
tokio = { version = "1.39.2", features = ["full"] }
urlencoding = "2.1.3"
uuid = { version = "1.11.0", features = ["v4"] }
